"""Exporters: full Markdown report and CSV extracts for saved analyses."""

from __future__ import annotations

import pandas as pd

from .template_engine import SECTION_ORDER


def to_markdown(ctx: dict) -> str:
    """Render the full analysis as a single Markdown document."""
    wf = ctx["workflow"]
    name = wf.get("workflow_name") or "Unnamed Workflow"
    lines = [
        f"# Workflow Improvement Package: {name}",
        "",
        f"*Generated by AI Workflow Waste Detector — {ctx['meta']['mode']}*  ",
        f"*Generated at: {ctx['meta']['generated_at']}*",
        "",
        f"**Waste Score:** {ctx['waste']['score']}/100 — {ctx['waste']['status']}  ",
        f"**Automation Readiness:** {ctx['automation']['score']}/100 — {ctx['automation']['status']}  ",
        f"**Improvement Priority:** {ctx['priority'][0]}",
        "",
        "---",
        "",
    ]

    for i, title in enumerate(SECTION_ORDER, start=1):
        body = ctx["sections"].get(title, "_Not generated._")
        lines.append(f"## {i}. {title}")
        lines.append("")
        lines.append(body)
        lines.append("")

    return "\n".join(lines)


def findings_dataframe(ctx: dict) -> pd.DataFrame:
    """Build a DataFrame of Lean waste findings."""
    findings = ctx.get("waste_findings", [])
    if not findings:
        return pd.DataFrame(
            columns=["Category", "Severity", "Observation", "Impact", "Recommendation"]
        )
    return pd.DataFrame(
        [
            {
                "Category": f["category"],
                "Severity": f["severity"],
                "Observation": f["observation"],
                "Impact": f["impact"],
                "Recommendation": f["recommendation"],
            }
            for f in findings
        ]
    )


def action_plan_dataframe(ctx: dict) -> pd.DataFrame:
    """Build a DataFrame of improvement action items."""
    actions = ctx.get("action_items", [])
    if not actions:
        return pd.DataFrame(
            columns=["Action", "Category", "Effort", "Impact", "Horizon", "Owner"]
        )
    return pd.DataFrame(
        [
            {
                "Action": a["title"],
                "Category": a["category"],
                "Effort": a["effort"],
                "Impact": a["impact"],
                "Horizon": a["horizon"],
                "Owner": a["owner"],
            }
            for a in actions
        ]
    )


def checklist_dataframe(ctx: dict) -> pd.DataFrame:
    """Build a DataFrame of the standard work checklist."""
    checklist = ctx.get("checklist", [])
    if not checklist:
        return pd.DataFrame(columns=["Checklist Item", "5S/6S Category", "Complete"])
    return pd.DataFrame(
        [
            {"Checklist Item": c["item"], "5S/6S Category": c["category"], "Complete": "No"}
            for c in checklist
        ]
    )


def future_state_dataframe(ctx: dict) -> pd.DataFrame:
    """Build a DataFrame of the recommended future-state steps."""
    steps = ctx.get("future_state_steps", [])
    if not steps:
        return pd.DataFrame(columns=["Step", "Future-State Recommendation"])
    return pd.DataFrame(
        [{"Step": i, "Future-State Recommendation": s} for i, s in enumerate(steps, start=1)]
    )


def dataframe_to_csv(df: pd.DataFrame) -> str:
    """Convert a DataFrame to a CSV string suitable for download."""
    return df.to_csv(index=False)
